# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Achivil's Blog
email: wy4u831@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This place is ready for remind something.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://achivil.gihub.io" # the base hostname & protocol for your site
twitter_username: achivil
# github_username:  achivil

# Build settings
markdown: kramdown
